### ISSUE TITLE
TypeError: promise.then is not a function

### ISSUE THREAD

**Issue by IgorMinar** [karma-runner/karma-dart#31]
I'm trying to upgrade angular/angular to karma-dart@0.3.0 and I'm getting:

```
 TypeError: promise.then is not a function
<     at [object Object].PromiseContainer.then (/Users/iminar/Dev/angular/node_modules/karma/lib/middleware/common.js:14:29)
<     at Object.handler (/Users/iminar/Dev/angular/karma-dart-evalcache.js:35:27)
<     at createCustomHandler (/Users/iminar/Dev/angular/node_modules/karma/lib/web-server.js:21:38)
<     at call (/Users/iminar/Dev/angular/node_modules/karma/node_modules/connect/index.js:239:7)
<     at next (/Users/iminar/Dev/angular/node_modules/karma/node_modules/connect/index.js:183:5)
<     at createProxy (/Users/iminar/Dev/angular/node_modules/karma/lib/middleware/proxy.js:94:14)
<     at call (/Users/iminar/Dev/angular/node_modules/karma/node_modules/connect/index.js:239:7)
<     at next (/Users/iminar/Dev/angular/node_modules/karma/node_modules/connect/index.js:183:5)
<     at /Users/iminar/Dev/angular/node_modules/karma/lib/middleware/source_files.js:44:9
<     at tryCatcher (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
<     at Promise.module.exports.Promise._settlePromiseFromHandler (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:507:31)
<     at Promise.module.exports.Promise._settlePromiseAt (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:581:18)
<     at Promise.module.exports.Promise._settlePromiseAtPostResolution (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:245:10)
<     at Async._drainQueue (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:128:12)
<     at Async._drainQueues (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
<     at Immediate.__dirname.drainQueues [as _onImmediate] (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
```

when I debugged the code, I noticed that the `promise` reference points to an object with two properties: 
```
> Object.keys(promise)
[ 'served', 'included' ]
```

Both of these properties point to arrays.

I don't know karma-dart code well, but it looks like something passes a non-promise object into `PromiseContainer#set`, which then causes this error.

**Comment by IgorMinar** [comment]
I should also mention that I'm upgrading karma-dart from 0.2.8 + node 0.12 to karma-dart 0.3.0 + node 4.1.1, but it's not likely that the node version is responsible for this.

**Comment by IgorMinar** [comment]
@zzo can you take a look at this please?

cc: @juliemr

**Comment by IgorMinar** [comment]
Looks like the bad object is being set via this code path:
```
Trace: bad object set
    at [object Object].set (/Users/iminar/Dev/angular/node_modules/karma/lib/middleware/common.js:24:46)
    at [object Object].<anonymous> (/Users/iminar/Dev/angular/karma-dart-evalcache.js:22:20)
    at emitOne (events.js:82:20)
    at [object Object].emit (events.js:169:7)
    at emit (/Users/iminar/Dev/angular/node_modules/karma/lib/file-list.js:76:19)
    at [object Object].self._emitModified (/Users/iminar/Dev/angular/node_modules/karma/lib/file-list.js:80:17)
    at /Users/iminar/Dev/angular/node_modules/karma/lib/file-list.js:202:10
    at tryCatcher (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/iminar/Dev/angular/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

the suspicious code in karma-dart-evalcache.js:

```
  function dartEvalCacheFactory(emitter, logger, customFileHandlers) {
    var filesPromise = new common.PromiseContainer();
    emitter.on('file_list_modified', function(files) {
      filesPromise.set(files);  // <<<<<<<< WHAT?!?!?
    });
```

**Comment by IgorMinar** [comment]
oh, wait. that's coming from angular! https://github.com/angular/angular/blob/master/karma-dart-evalcache.js

false alarm folks.. sorry.
